site_name: CIS-CAT Pro Assessor v4

nav:
  - Home: index.md
  - User's Guide: CIS-CAT Pro Assessor v4 Users Guide.md
  - Configuration Guide: CIS-CAT Pro Assessor v4 Configuration Guide.md
  - Coverage Guide: CIS-CAT Pro Assessor v4 Coverage Guide.md
  - 3rd-Party Licenses: CIS-CAT Pro Assessor v4 License Information.md
  - Change Log: CIS-CAT Pro Assessor v4 CHANGELOG.md

theme: readthedocs
